-- MySQL Script generated by MySQL Workbench
-- Mon Apr 24 16:04:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BD_CARERAS
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `BD_CARERAS` ;

-- -----------------------------------------------------
-- Schema BD_CARERAS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD_CARERAS` DEFAULT CHARACTER SET utf8 ;
USE `BD_CARERAS` ;

-- -----------------------------------------------------
-- Table `BD_CARERAS`.`Universidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_CARERAS`.`Universidades` (
  `id_univ` INT NOT NULL,
  `NIF` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_univ`),
  UNIQUE INDEX `NIF_UNIQUE` (`NIF` ASC) VISIBLE)
ENGINE = InnoDB;

ALTER TABLE BD_CARRERAS.Univeridades
ADD CONSTRAINT ck_Universidades_Tipo CHECK (Tipo IN ("PUB", "PRV"));

-- -----------------------------------------------------
-- Table `BD_CARERAS`.`Carreras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_CARERAS`.`Carreras` (
  `codigo_car` CHAR(3) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Nivel` CHAR(1) NOT NULL,
  `Duracion` INT NULL,
  `Universidades_id_univ` INT NOT NULL,
  PRIMARY KEY (`codigo_car`),
  INDEX `fk_Carreras_Universidades1_idx` (`Universidades_id_univ` ASC) VISIBLE,
  CONSTRAINT `fk_Carreras_Universidades1`
    FOREIGN KEY (`Universidades_id_univ`)
    REFERENCES `BD_CARERAS`.`Universidades` (`id_univ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE BD_CARRERAS.Carreras
ADD CONSTRAINT ck_Universidades_Nivel CHECK (Nivel IN ("G", "P"));

ALTER TABLE BD_CARRERAS.Carreras
ADD CONSTRAINT ck_Universidades_Duracion CHECK (Duracion BETWEEN 1 AND 5);

-- -----------------------------------------------------
-- Table `BD_CARERAS`.`Asignaturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_CARERAS`.`Asignaturas` (
  `codigo_asig` CHAR(5) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Semestre` INT NOT NULL,
  `Codigo_car` CHAR(3) NOT NULL,
  PRIMARY KEY (`codigo_asig`),
  INDEX `fk_Asignaturas_Carreras_idx` (`Codigo_car` ASC) VISIBLE,
  CONSTRAINT `fk_Asignaturas_Carreras`
    FOREIGN KEY (`Codigo_car`)
    REFERENCES `BD_CARERAS`.`Carreras` (`codigo_car`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE BD_CARRERAS.Asignaturas
ADD CONSTRAINT ck_Universidades_Semestre CHECK (Semestre BETWEEN 1 AND 10);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
